### ISSUE TITLE
Lightstreamer: Sending to a port 

### ISSUE THREAD

**Issue by lezwright** [gfiocco/node-ig-api#7]
Hi @gfiocco , many thanks for such a wonderful package. I say it is the only one that actually works. I need to change the output of Lightstreamer instead of getting a log to sending it to a port. I changed the ``subscribeToLightstreamer()`` function in index.js as follows to get a json output

![image](https://user-images.githubusercontent.com/61321682/86845819-f0c60b80-c0a1-11ea-90da-c83bbe149cd3.png)

Do you have any suggestion how to modify it to listen to port rather than writing it in a file?

**Comment by gfiocco** [comment]
You first need some app to listen to a port before directing the Lightstreamer subscription output to that port. At that point, it would be more efficient subscribing to the Lightstreamer within the app itself. Else, you can try using a WebSocket for piping the Lightstreamer subscription output into your app which is listening at some port, but then again, ending up in the chicken or the egg causality dilemma.
